
fqsuffix: "fastq.gz"
fqext1: "R1"
fqext2: "R2"

paired: True
length: 150

fq_dir: "Raw_fastq"
ref: "genome.fa"
gtf: "genes.gtf"

### Do you have library prep tech reps- these will be merged together
## sample names must be different
tech_reps: False
sample_sheet: "units_no_techreps.tsv"

fdr: 0.05

annotation: "hg19"


cutadapt-pe:
  r1_adapter: "AGAGCACACGTCTGAACTCCAGTCAC"
  r2_adapter: "AGATCGGAAGAGCACACGT"
  params: "-q 0 -m 20"

cutadapt-se:
  r1_adapter: "AGAGCACACGTCTGAACTCCAGTCAC"
  params: "-q 0 -m 20"  

outdir: "RNA-Seq_analysis_2"
#RNA solo ovation
#  params: "--clip_R1 5"

aligner: 'STAR'
## choose between hisat2 or STAR

star_mapping:
  params:
  threads: 10

hisat2_mapping:
  other:
  threads: 10
  index: "/lower_bay/local_storage/annotation_db/Mus_Musculus/UCSC/mm10/Sequence/newHisat/genome" 
  strand: "unstranded"
  ## other options: R RF

cuffnorm:
  threads: 10
  lib: 'fr-unstranded'

## choices  
## "fr-unstranded"
## "fr-secondstrand",
## "fr-firststrand"]
featureCounts:
  threads: 10
  other: "-p" ## paired
  strand: 0 

## choices:
## "0"
## "1"
## "2"

resources:
  star:
      mem: 300G
      time: "2:00:00"
      cpus: 16
  hisat:
      mem: 300G
      time: "2:00:00"
      cpus: 16      
  featureCounts:
      mem: 200G
      time: "1:30:00"
      cpus: 16   
  cuffnorm:
      mem: 200G
      time: "5:00:00"
      cpus: 16  
  bamCov:
      mem: 200G
      time: "1:00:00"
      cpus: 16 
  samtools:
      mem: 200G
      time: "1:00:00" 
      cpus: 16
     