
fqsuffix: "fastq"
fqext1: "R1"
fqext2: "R2"

paired: True
length: 150


cutadapt-pe:
  r1_adapter: "AGAGCACACGTCTGAACTCCAGTCAC"
  r2_adapter: "AGATCGGAAGAGCACACGT"
  params: "-q 0 -m 20"

cutadapt-se:
  r1_adapter: "AGAGCACACGTCTGAACTCCAGTCAC"
  params: "-q 0 -m 20"  

outdir: "RNA-Seq_results"
#RNA solo ovation
#  params: "--clip_R1 5"

aligner: 'STAR'
## choose between hisat2 or STAR

star_mapping:
  params:
  threads: 10

hisat2_mapping:
  other:
  threads: 10
  index: "/lower_bay/local_storage/annotation_db/Mus_Musculus/UCSC/mm10/Sequence/newHisat/genome" 
  strand: "unstranded"
  ## other options: R RF

cuffnorm:
  threads: 10
  lib: 'fr-unstranded'

## choices  
## "fr-unstranded"
## "fr-secondstrand",
## "fr-firststrand"]
featureCounts:
  threads: 10
  other: "-p" ## paired
  strand: 0 

## choices:
## "0"
## "1"
## "2"

raw_data: "."
ref: "genome.fa"
gtf: "genes.gtf"

units: "units.tsv"

fdr: 0.05

annotation: "hg19"

