channels:
  - conda-forge
  - bioconda
  - r

dependencies:
  - trimmomatic=0.39
  - star=2.7.2a
  - fastqc
  - subread
  - cufflinks=2.2.1
  - multiqc
  - bioconda::bioconductor-deseq2=1.28.1
  - deeptools
  - pandas
  - snakemake=5.25
  - r-base=4.0.1
  - r-ggplot2=3.3.2
  - r-tidyverse=1.3.0
  - r-gplots
  - bioconda::bioconductor-clusterprofiler=3.16.1
  - r-RColorBrewer
  - r-scales
        
