channels:
  - conda-forge
  - bioconda
  - r

dependencies:
  - trimmomatic=0.39
  - star=2.7.2a
  - samtools=1.10
  - fastqc
  - subread
  - cufflinks=2.2.1
  - multiqc
  - deeptools
  - pandas
  - snakemake=5.25
  - pandas_schema  
  - r-base=4.0.3
  - r-tidyverse=1.3
  - r-gplots=3.1
  - bioconductor-clusterprofiler=3.18
  - r-RColorBrewer=1.1
  - r-scales=1.1
  - r-ggnewscale = 0.4
  - bioconductor-deseq2=1.30
  - bioconductor-do.db=2.9=r40_9
  - bioconductor-rWikiPathways=1.10
  - bioconductor-spia=2.42
        
